// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2uLc2Op3l--Bu8YF__BtbwAqpXML-WlM',
    appId: '1:793015419229:web:ae71b365774ca7b0d028b4',
    messagingSenderId: '793015419229',
    projectId: 'mikan-17ec1',
    authDomain: 'mikan-17ec1.firebaseapp.com',
    storageBucket: 'mikan-17ec1.appspot.com',
    measurementId: 'G-5FQV717YMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq_KG02Sfcpy2frmr4IX63vyjuBdjV3XM',
    appId: '1:793015419229:android:b74c6067719309b9d028b4',
    messagingSenderId: '793015419229',
    projectId: 'mikan-17ec1',
    storageBucket: 'mikan-17ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBivShsGiZXp4aj-pdbQyMXc38Wek2l-p4',
    appId: '1:793015419229:ios:176840a524b6deb3d028b4',
    messagingSenderId: '793015419229',
    projectId: 'mikan-17ec1',
    storageBucket: 'mikan-17ec1.appspot.com',
    iosBundleId: 'com.example.mikan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBivShsGiZXp4aj-pdbQyMXc38Wek2l-p4',
    appId: '1:793015419229:ios:abe0309d466e3bf8d028b4',
    messagingSenderId: '793015419229',
    projectId: 'mikan-17ec1',
    storageBucket: 'mikan-17ec1.appspot.com',
    iosBundleId: 'com.example.mikan.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2uLc2Op3l--Bu8YF__BtbwAqpXML-WlM',
    appId: '1:793015419229:web:96e428010bd634dbd028b4',
    messagingSenderId: '793015419229',
    projectId: 'mikan-17ec1',
    authDomain: 'mikan-17ec1.firebaseapp.com',
    storageBucket: 'mikan-17ec1.appspot.com',
    measurementId: 'G-JL4885ZTP9',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyC2uLc2Op3l--Bu8YF__BtbwAqpXML-WlM',
    appId: '1:793015419229:web:b4927525cc600e10d028b4',
    messagingSenderId: '793015419229',
    projectId: 'mikan-17ec1',
    authDomain: 'mikan-17ec1.firebaseapp.com',
    storageBucket: 'mikan-17ec1.appspot.com',
    measurementId: 'G-TKE02VFDR4',
  );
}
